name: Build and Deploy Angular App to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build -- --output-path=./dist/out --base-href=/daily-torah/

    - name: Deploy
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        publish_dir: ./dist/out
